name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4', '8.0']
        dependencies: ['', '--prefer-lowest']
    
    name: PHP ${{ matrix.php }} ${{ matrix.dependencies }}
    
    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: testing
          MYSQL_USER: root
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, json, mbstring, tokenizer, mysql
          coverage: none
        
      - name: Validate composer.json and composer.lock
        run: composer validate
      
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
            
      - name: Remove composer.lock
        run: rm -rf composer.lock

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --no-progress ${{ matrix.dependecies }}
        
      - name: Start mysql service
        run: sudo /etc/init.d/mysql start
        
      - run: mysql < ./tests/testing.sql -u root
      - run: vendor/bin/tester -C tests
